# Whether to use periodic boundary condition in each direction
periodic_boundary = [true, true]

# This section describes the grid parameters. Every parameter is an array with 3
# elements, describing the number for each dimension. If you wish to disable one
# dimension, just set N to 1 and guard to 0 on that dimension.
[Grid]
# Number of grid points in each direction, excluding guard cells
N = [10, 10, 1]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard
guard = [2, 2, 0]

# Number of ranks for domain decomp in each directions
nodes = [2, 2, 1]

# Lower limit of the coordinate
lower = [1.0, 2.0, 3.0]

# Size of the box in each dimension
size = [100.0, 10.0, 2.0]

# Size of a tile of cells
tile_size = [64, 64, 1]
