# Time step size
delta_t = 0.001

# Whether to use periodic boundary condition in each direction
periodic_boundary = [false, false, true]

# Data output directory
data_dir = "/home/alex/storage/Data/FFEsph/"

# Dipole B0
B0 = 1000.0

# Star rotating omega
omega = 0.1

ph_buffer_size = 1

ptc_buffer_size = 1

# This section describes the grid parameters. Every parameter is an array with 3
# elements, describing the number for each dimension. If you wish to disable one
# dimension, just set N to 1 and guard to 0 on that dimension.
[Grid]
# Number of grid points in each direction, excluding guard cells. This should be
# a power of 2.
N = [256, 256, 512]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard. Minimum 2 is required!
guard = [4, 4, 4]

# Lower limit of the coordinate
lower = [0.0, 0.15, 0.0]

# Size of the box in each dimension
size = [3.5, 2.8415926535898, 6.283185307179586]

[Simulation]

coord_system = "LogSpherical"

random_seed = 3333

downsample = 2

max_steps = 200

data_interval = 10