# Time step size
delta_t = 1.0e-4

# Charge of an electron
q_e = 1.0

# Number of species
num_species = 2

# Maximum number of particles per node
max_ptc_number = 180000000

# Maximum number of photons per node
max_photon_number = 180000000

# Create pairs or not
create_pairs = true

# Trace photons or not
trace_photons = true

# Threshold for creating a photon / pair
gamma_thr = 30.0

# Free path for energetic photons
photon_path = 0.5

# Secondary particle energy
E_secondary = 6.0

# Minimum photon enery
E_ph_min = 10.0

# Radius cutoff for pair creation
r_cutoff = 3.0

# Free path for inverse Compton once a particle reaches threshold
ic_path = 0.1

# Spectral index alpha for the background soft photon
spectral_alpha = 1.2

# Minimum energy for the above power law soft photon
e_min = 1.0e-5

# Separation between two energy regimes for inverse Compton scattering
e_s = 0.2

# Whether to use periodic boundary condition in each direction
periodic_boundary = [false, false]

# Fraction of total particles to track
track_percent = 0.1

# Data output directory
data_dir = "/home/alex/storage/Data/1DGR/1d_experiment"

# Dipole B0
B0 = 1.0e7

# Damping coefficient
damping_coef = 0.003

# Damping layer thickness in cells
damping_length = 32

# Star rotating omega
omega = 0.2117

# Resolution for gamma grid used in IC scattering table
n_gamma = 300

# Resolution for photon energy grid used in IC table
n_ep = 300

# Temperature of the background soft photon
star_kT = 1e-4

# This section describes the grid parameters. Every parameter is an array with 3
# elements, describing the number for each dimension. If you wish to disable one
# dimension, just set N to 1 and guard to 0 on that dimension.
[Grid]
# Number of grid points in each direction, excluding guard cells. This should be
# a power of 2.
N = [16384, 1, 1]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard. Minimum 2 is required!
guard = [2, 0, 0]

# Lower limit of the coordinate
lower = [-6.273, 0.0, 0.0]

# Size of the box in each dimension
size = [6.138, 1.0, 1.0]

[Simulation]

coord_system = "1DGR"

random_seed = 3333

downsample = 1

max_steps = 1000000

data_interval = 1000

sort_interval = 20

current_smoothing = 8
