# Time step size
delta_t = 0.001

# Charge of an electron
q_e = 16000.0

# Ion mass
ion_mass = 1.0

# Number of species
num_species = 3

# Maximum number of particles per node
max_ptc_number = 230000000

# Maximum number of photons per node
max_photon_number = 50000000

# Create pairs or not
create_pairs = true

# Trace photons or not
trace_photons = true

# Threshold for creating a photon / pair
gamma_thr = 25.0

# Free path for energetic photons
photon_path = 0.02

# Secondary particle energy
E_secondary = 4.0

# Radius cutoff for pair creation
r_cutoff = 3.0

# Gravity switch
gravity_on = true

# Gravity strength
gravity = 0.1

# Stellar compactness: r_g / R_*
compactness = 0.0

# Radiation cooling switch
rad_cooling_on = true

# Radiation cooling strength
rad_cooling_coef = 0.05

# Whether to use periodic boundary condition in each direction
periodic_boundary = [false, false]

# Data output directory
data_dir = "/home/alex/storage/Data/Aperture3/2d_wp_experiment/"
# data_dir = "/home/alex/storage/Data/Aperture3/2d_sync_experiment/"
# data_dir = "/home/alex/storage/Data/Aperture3/gr_monopole/"

# Dipole B0
B0 = 160000.0

# Dipole B0
BQ = 3200000.0

# Damping coefficient
damping_coef = 0.002

# Damping layer thickness in cells
damping_length = 96

# Star rotating omega
omega = 0.125
# omega = 0.0

# Whether to inject ions or positrons
inject_ions = true

# fraction of particles to track
track_percent = 0.01

# curvature emission free path
l_curv = 6.0

# curvature photon characteristic energy
# e_curv = 6.4e-9
e_curv = 4.5e-7

# curvature photon characteristic free path
l_ph = 0.01

# This section describes the grid parameters. Every parameter is an array with 3
# elements, describing the number for each dimension. If you wish to disable one
# dimension, just set N to 1 and guard to 0 on that dimension.
[Grid]
# Number of grid points in each direction, excluding guard cells. This should be
# a power of 2.
# N = [2048, 2048, 1]
N = [1536, 1536, 1]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard. Minimum 2 is required!
guard = [3, 3, 0]

# Lower limit of the coordinate
lower = [0.0, 0.0, 0.0]

# Size of the box in each dimension
size = [3.4, 3.1415926535898, 1.0]

# Size of a tile of cells
tile_size = [16, 16, 1]

[Simulation]

coord_system = "LogSpherical"

random_seed = 3333

# Downsample factor. 1 means no downsample at all, and n means output
# resolution is divided by n. This should be a power of 2 as well
downsample = 3

max_steps = 200000

data_interval = 200

snapshot_interval = 5000

sort_interval = 20

current_smoothing = 2

update_fields = true

inject_particles = true
