# Time step size
delta_t = 0.0005

# Charge of an electron
q_e = 400.0

# Ion mass
ion_mass = 5.0

# Number of species
num_species = 3

# Maximum number of particles per node
max_ptc_number = 150000000

# Maximum number of photons per node
max_photon_number = 20000000

# Create pairs or not
create_pairs = true

# Trace photons or not
trace_photons = true

# Threshold for creating a photon / pair
gamma_thr = 20.0

# Free path for energetic photons
photon_path = 0.01

# Secondary particle energy
E_secondary = 8.0

# Radius cutoff for pair creation
r_cutoff = 2.0

# Gravity switch
gravity_on = true

# Gravity strength
gravity = 1.0

# Stellar compactness: r_g / R_*
compactness = 0.5

# Radiation cooling switch
rad_cooling_on = true

# Radiation cooling strength
rad_cooling_coef = 2.0e-10

# Whether to use periodic boundary condition in each direction
periodic_boundary = [false, false]

# Data output directory
data_dir = "/home/alex/storage/Data/Aperture3/2d_weak_pulsar/"

# Dipole B0
B0 = 160000.0

# Damping coefficient
damping_coef = 0.003

# Damping layer thickness in cells
damping_length = 48

# Star rotating omega
omega = 0.125

# This section describes the grid parameters. Every parameter is an array with 3
# elements, describing the number for each dimension. If you wish to disable one
# dimension, just set N to 1 and guard to 0 on that dimension.
[Grid]
# Number of grid points in each direction, excluding guard cells. This should be
# a power of 2.
N = [2048, 2048, 1]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard. Minimum 2 is required!
guard = [2, 2, 0]

# Lower limit of the coordinate
lower = [0.0, 0.0, 0.0]

# Size of the box in each dimension
size = [4.0, 3.1415926535898, 1.0]

# Size of a tile of cells
tile_size = [16, 16, 1]

[Simulation]

coord_system = "LogSpherical"

random_seed = 3333

# Downsample factor. 1 means no downsample at all, and n means output
# resolution is divided by n. This should be a power of 2 as well
downsample = 4

max_steps = 2000000

data_interval = 400

snapshot_interval = 5000

sort_interval = 20
