# Time step size
delta_t = 0.00075

# Charge of an electron
q_e = 100.0

# Ion mass
ion_mass = 10.0

# Number of species
num_species = 3

# Maximum number of particles per node
max_ptc_number = 200000000

# Maximum number of photons per node
max_photon_number = 100000000

# Create pairs or not
create_pairs = true

# Trace photons or not
trace_photons = true

# Threshold for creating a photon / pair
gamma_thr = 30.0

# Free path for energetic photons
photon_path = -0.01

# Secondary particle energy
E_secondary = 6.0

# Radius cutoff for pair creation
r_cutoff = 3.0

# Minimum photon energy that counts
E_ph_min = 2.1

# Gravity switch
gravity_on = false

# Gravity strength
gravity = 1.0

# Radiation cooling switch
rad_cooling_on = true

# Radiation cooling strength
rad_cooling_coef = 1.0

# Whether to use periodic boundary condition in each direction
periodic_boundary = [false, false]

# Fraction of total particles to track
track_percent = 0.1

# Data output directory
data_dir = "/home/alex/storage/Data/Aperture3/magnetar"

# Dipole B0
B0 = 120000.0

# Quantum Field BQ
BQ = 12000.0

# Resonant drag coefficient
res_drag_coef = 4000.0

# Stellar temperature kT
star_kT = 0.008

# Damping coefficient
damping_coef = 0.003

# Damping layer thickness in cells
damping_length = 48

# Star rotating omega
omega = -0.03

# This section describes the grid parameters. Every parameter is an array with 3
# elements, describing the number for each dimension. If you wish to disable one
# dimension, just set N to 1 and guard to 0 on that dimension.
[Grid]
# Number of grid points in each direction, excluding guard cells. This should be
# a power of 2.
N = [1536, 1536, 1]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard. Minimum 2 is required!
guard = [2, 2, 0]

# Lower limit of the coordinate
lower = [0.0, 0.0, 0.0]

# Size of the box in each dimension
size = [4.0, 3.1415926535898, 1.0]

# Size of a tile of cells
tile_size = [16, 16, 1]

[Simulation]

coord_system = "LogSpherical"

random_seed = 3333

# Downsample factor. 1 means no downsample at all, and n means output
# resolution is divided by n. This should be a power of 2 as well
downsample = 4

max_steps = 400000

data_interval = 400

snapshot_interval = 5000

sort_interval = 10
